name: DOWS6027 PDF Automation

on:
  workflow_dispatch: # manual trigger
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  run_dows6027_pdf:
    runs-on: ubuntu-latest
    env:
      run_mode: run
      DOWS_DRIVE_FOLDER_ID: ${{ secrets.DOWS_DRIVE_FOLDER_ID }}
      SAPHAH_EMAIL_PASS: ${{ secrets.SAPHAH_EMAIL_PASS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install node-fetch puppeteer jsdom googleapis nodemailer date-fns fs-extra

      - name: Run DOWS6027 PDF Automation
        run: node dows6027-pdf.js
